config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "lists#index"
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, scope: :list_id
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmark_controller.rb
class BookmarkController < ApplicationController
  before_action :set_list, only: :create

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to root_path(@list)
    else
      render 'list/show', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to root_path(@bookmark.list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: :create

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to root_path(@list)
    else
      render 'list/show', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to root_path(@bookmark.list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/list_controller.rb
class ListController < ApplicationController
  before_action :set_list, only: %i[show]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to rooth_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :image_url)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to root_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/bookmark/new.html.erb
 <%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie, prompt: "Select a Movie" %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>
<%= link_to 'Go back to list', list_path(@list) %>

app/views/bookmarks/_form.html.erb
 <%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie, prompt: "Select a Movie" %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>
<%= link_to 'Go back to list', list_path(@list) %>

app/views/bookmarks/new.html.erb
<h1>Create Bookmark for <%= @list.name %></h1>
<%= render "form", list: @list, bookmark: @bookmark %>
<hr />
<%= link_to 'Back to main list', list_path(@list) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/list/_form.html.erb
<%= simple_form_for [@list] do |f| %>
  <%= f.input :name %>
  <%= f.input :image_url, as: :url %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/list/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1574267432553-4b4628081c31);">
  <div class="container">
    <h1>Save any kind of movies</h1>
  </div>
</div>
<div class="container py-5">
  <div class="row">
    <div class="col-md-9">
      <h2>My lists</h2>
      <div id="lists" class="row">
        <% @lists.each do |list| %>
          <div class="col-sm-6">
            <% image = list.image_url.nil? || list.image_url.empty? ? "https://images.unsplash.com/photo-1543536448-d209d2d13a1c" : list.image_url %>
            <div class="card-category mb-4" style="background-image: url(<%= image %>)">
              <%= link_to list_path(list) do %>
                <%= list.name %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-3">
      <%= link_to raw('<i class="fa-solid fa-plus"></i> Create a list'), new_list_path, class: 'btn d-block btn-primary btn-lg py-3' %>
    </div>
  </div>
</div>

app/views/list/show.html.erb
<% image = @list.image_url.nil? || @list.image_url.empty? ? "https://images.unsplash.com/photo-1543536448-d209d2d13a1c" : @list.image_url %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image %>);">
  <div class="container">
    <h1><%= @list.name %></h1>
    <span class="position-absolute top-0 end-0 mt-4 me-4 badge bg-warning"><%= pluralize(@list.movies.size, "movie") %></span>
  </div>
</div>
<div class="container py-5">
  <div class="d-flex justify-content-between">
    <%= link_to raw('<i class="fa-solid fa-chevron-left"></i> Go back to lists'), lists_path, class: 'btn btn-primary mb-4 me-1' %>
    <a href="#bookmark-form" class="btn btn-primary mb-4 ms-1"><i class="fa-solid fa-plus"></i> Add a movie</a>
  </div>
  <%= raw("<h2>You haven't saved any movies yet!</h2>") if @list.movies.empty? %>

  <div class="row my-2">
    <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
      <div class="col-12 col-sm-6 mb-4">
        <div class="bg-white rounded shadow-sm h-100">
          <%= image_tag movie.poster_url, alt: movie.title, class: "movie-img rounded-top" %>
          <div class="p-3 rounded-bottom d-flex flex-column">
            <strong><%= movie.title %> <span class="text-muted font-weight-normal">• <%= movie.rating %> <i class="fas fa-star star-yellow"></i></span></strong>
            <small class="text-muted"><%= movie.overview %></small>
            <div class="d-flex align-items-end justify-content-between pt-4">
              <div>
                <i class="fas fa-quote-left me-2"></i><small class="flex-grow-1"><%= bookmark.comment %></small>
              </div>
              <small class="text-right flex-shrink-0"><%= link_to "delete", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"}, class: 'text-danger' %></small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <hr />
  <div class="py-3" id="bookmark-form">
    <h2>Create Bookmark for <%= @list.name %></h2>
    <%= render "bookmarks/form", list: @list, bookmark: @bookmark %>
  </div>
</div>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/lists/index.html.erb
<h1>Save a movie</h1>
<div class="container py-5">
  <div class="row">
    <div class="col-md-9">
      <h2>All lists</h2>
      <div id="lists" class="row">
        <% @lists.each do |list| %>
          <div class="col-sm-6">
           <% if list.photo.attached? %>
        <%= cl_image_tag list.photo.key,width: 300, height: 200, crop: :fill, class: "card-img-top" %>
        <% else %>
        <%= image_tag "https://res.cloudinary.com/dixe4r20z/image/upload/v1666742117/cld-sample-2.jpg",width: 300, height: 200, crop: :fill, class: "card-img-top" %>
        <% end %>
              <%= link_to list_path(list) do %>
                <%= list.name %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-3">
      <%= link_to raw('<i class="fa-solid fa-plus"></i> Create a list'), new_list_path, class: 'btn d-block btn-primary btn-lg py-3' %>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white p-3 rounded">
        <h1>Create List</h1>
        <%= render "form", list: @list %>
        <hr />
        <%= link_to 'Go back to lists', lists_path %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
  <div class="container">
    <h1><%= @list.name %></h1>
    <span class="position-absolute top-0 end-0 mt-4 me-4 badge bg-warning"><%= pluralize(@list.movies.size, "movie") %></span>
  </div>
</div>
<div class="container py-5">
  <div class="d-flex justify-content-between">
    <%= link_to raw('<i class="fa-solid fa-chevron-left"></i> Go back to lists'), lists_path, class: 'btn btn-primary mb-4 me-1' %>
  </div>
  <%= raw("<h2>You haven't saved any movies yet!</h2>") if @list.movies.empty? %>

  <div class="row my-2">
    <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
      <div class="col-12 col-sm-6 mb-4">
        <div class="bg-white rounded shadow-sm h-100">
          <%= image_tag movie.poster_url, alt: movie.title, class: "movie-img rounded-top" %>
          <div class="p-3 rounded-bottom d-flex flex-column">
            <strong><%= movie.title %> <span class="text-muted font-weight-normal">• <%= movie.rating %> <i class="fas fa-star star-yellow"></i></span></strong>
            <small class="text-muted"><%= movie.overview %></small>
            <div class="d-flex align-items-end justify-content-between pt-4">
              <div>
                <i class="fas fa-quote-left me-2"></i><small class="flex-grow-1"><%= bookmark.comment %></small>
              </div>
              <small class="text-right flex-shrink-0"><%= link_to "delete", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"}, class: 'text-danger' %></small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <hr />
  <div class="py-3" id="bookmark-form">
    <h2>Create Bookmark for <%= @list.name %></h2>
    <%= render "bookmarks/form", list: @list, bookmark: @bookmark %>
  </div>
</div>